// LOCALHOST
### 
GET http://localhost:8080/contacts
### 
GET http://localhost:8080/contacts/632dd81444f5a2eb27698d9d
### 
GET http://localhost:8080/contacts/632dd81444f5a2eb27698d9e
### 
GET http://localhost:8080/contacts/632dd81444f5a2eb27698d9f

// PRODUCTION Deploy
### 
GET https://cse-341-w02.onrender.com/contacts
### 
GET https://cse341-instructor.herokuapp.com/contacts/632dd81444f5a2eb27698d9d
### 
GET https://cse341-instructor.herokuapp.com/contacts/632dd81444f5a2eb27698d9e
### 
GET https://cse341-instructor.herokuapp.com/contacts/632dd81444f5a2eb27698d9f